export const WEB3AUTH_CLIENT_ID = process.env.EXPO_PUBLIC_WEB3AUTH_CLIENT_ID;

export const BUNDLER_URL = process.env.EXPO_PUBLIC_BUNDLER_URL!;
export const ENTRYPOINT_ADDRESS = process.env.EXPO_PUBLIC_ENTRYPOINT_ADDRESS!;

export const SIMPLE_ACCOUNT_FACTORY_ADDRESS =
  process.env.EXPO_PUBLIC_SIMPLE_ACCOUNT_FACTORY_ADDRESS!;

export const USE_PAYMASTER = process.env.EXPO_PUBLIC_USE_PAYMASTER!;
export const PAYMASTER_URL = process.env.EXPO_PUBLIC_PAYMASTER_URL!;
